// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://injvwmsqinrcthgdlvux.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImluanZ3bXNxaW5yY3RoZ2RsdnV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MDM0OTAsImV4cCI6MjA3MDQ3OTQ5MH0.tQAUNFiCU9sZXDbwpI8l5UXEealwu1Iuj5KrHCYWa8Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});